fix yaml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,5 +1,4 @@
-defaults:              &defaults
-  #working_directory:  ./circleci
+defaults: &defaults #working_directory: ./circleci
   docker:
     - image:           circleci/node:8
 
@@ -12,7 +11,7 @@ jobs:
       # Download and cache dependencies
       - restore_cache:
           keys:
-          - v1-dependencies-{{ checksum "package.json" }}
+            - v1-dependencies-{{ checksum "package.json" }}
       - run:           npm install
       - save_cache:
           paths:
@@ -28,7 +27,7 @@ jobs:
       - checkout
       - attach_workspace:
           at:          .
-      - run:           npm run build
+      - run:           yarn build
       - persist_to_workspace:
           root:        .
           paths:
@@ -39,21 +38,21 @@ jobs:
       - checkout
       - attach_workspace:
           at:          .
-      - run:           npm run test
+      - run:           yarn test
   e2e:
     <<:                *defaults
     steps:
       - checkout
       - attach_workspace:
           at:          .
-      - run:           npm run test
+      - run:           yarn test
   lint:
     <<:                *defaults
     steps:
       - checkout
       - attach_workspace:
           at:          .
-      - run:           npm run lint
+      - run:           yarn lint
   deploy-github:
     <<:                *defaults
     steps:
@@ -63,41 +62,41 @@ jobs:
       - deploy:
           name:        Deploy to GitHub Pages
           command:     |
-              set -e
+            set -e
 
-              remote=$(git config remote.origin.url)
+            remote=$(git config remote.origin.url)
 
-              if [ ! -d "build" ]
-              then
-                  echo "build folder not found"
-                  exit 1
-              fi
+            if [ ! -d "build" ]
+            then
+                echo "build folder not found"
+                exit 1
+            fi
 
-              mkdir gh-pages-branch
-              cd gh-pages-branch
-              git config --global user.email "$GH_EMAIL" > /dev/null 2>&1
-              git config --global user.name "$GH_NAME" > /dev/null 2>&1
-              git init
-              git remote add --fetch origin "$remote"
+            mkdir gh-pages-branch
+            cd gh-pages-branch
+            git config --global user.email "$GH_EMAIL" > /dev/null 2>&1
+            git config --global user.name "$GH_NAME" > /dev/null 2>&1
+            git init
+            git remote add --fetch origin "$remote"
 
-              if git rev-parse --verify origin/gh-pages > /dev/null 2>&1
-              then
-                  git checkout gh-pages
-                  git rm -rf .
-              else
-                  git checkout --orphan gh-pages
-              fi
+            if git rev-parse --verify origin/gh-pages > /dev/null 2>&1
+            then
+                git checkout gh-pages
+                git rm -rf .
+            else
+                git checkout --orphan gh-pages
+            fi
 
-              cp -a "../build/." .
+            cp -a "../build/." .
 
-              git add -A
-              git commit --allow-empty -m "Deploy to GitHub pages [ci skip]"
-              git push --force --quiet origin gh-pages > /dev/null 2>&1
+            git add -A
+            git commit --allow-empty -m "Deploy to GitHub pages [ci skip]"
+            git push --force --quiet origin gh-pages > /dev/null 2>&1
 
-              cd ..
-              rm -rf gh-pages-branch
+            cd ..
+            rm -rf gh-pages-branch
 
-              echo "Finished GitHub pages Deployment!"
+            echo "Finished GitHub pages Deployment!"
 
   deploy-prod:
     <<:                *defaults
@@ -108,8 +107,7 @@ jobs:
       - deploy:
           name:        Deploy to Production
           command:     |
-              echo "iooooooo"
-
+            echo "iooooooo"
 
 workflows:
   version:             2
@@ -137,69 +135,3 @@ workflows:
           requires:
             - tu
             - e2e
-
-
-# version:             2
-# jobs:
-#   build:
-#     branches:
-#       ignore:
-#         - gh-pages
-#     docker:
-#       - image:       circleci/node:8
-#     working_directory: ~/repo
-#     steps:
-#       - checkout
-#       - restore_cache:
-#           keys:
-#           - dependencies-{{ checksum "package.json" }}
-#           - dependencies-
-#       - run:
-#           name:      Install dependencies
-#           command:   npm install
-#       - save_cache:
-#           paths:
-#             - node_modules
-#           key:       dependencies-{{ checksum "package.json" }}
-#       - deploy:
-#           name:      Deploy
-#           command:   |
-#               set -e
-#               npm install
-#               CI="" npm run build
-
-#               remote=$(git config remote.origin.url)
-
-#               siteSource="build"
-
-#               if [ ! -d "build" ]
-#               then
-#                   echo "Usage: $0 <site source dir>"
-#                   exit 1
-#               fi
-
-#               mkdir gh-pages-branch
-#               cd gh-pages-branch
-#               git config --global user.email "$GH_EMAIL" > /dev/null 2>&1
-#               git config --global user.name "$GH_NAME" > /dev/null 2>&1
-#               git init
-#               git remote add --fetch origin "$remote"
-
-#               if git rev-parse --verify origin/gh-pages > /dev/null 2>&1
-#               then
-#                   git checkout gh-pages
-#                   git rm -rf .
-#               else
-#                   git checkout --orphan gh-pages
-#               fi
-
-#               cp -a "../build/." .
-
-#               git add -A
-#               git commit --allow-empty -m "Deploy to GitHub pages [ci skip]"
-#               git push --force --quiet origin gh-pages > /dev/null 2>&1
-
-#               cd ..
-#               rm -rf gh-pages-branch
-
-#               echo "Finished Deployment!"
